### ISSUE TITLE
Build-server error not working on Mac 

### ISSUE THREAD

**Issue by hanoisteve** [venilnoronha/grpc-web-istio-demo#2]
he command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o bin/server ./cmd/server.go' returned a non-zero code: 2
make: *** [build-server] Error 2

**Comment by venilnoronha** [comment]
What version of Docker are you using? I can confirm that this works for me on Mac. Mind posting the detailed log?

**Comment by hanoisteve** [comment]
Sure, I have posted full outputs below. I also tried adding to the top of Dockerfile

    from golang:latest as builder

and running    sudo make build-server

per this issue  https://github.com/golang/dep/issues/2083

but I still get the error.

Macbook pro. High Sierra. 10.13.6
coffee:grpc-web-istio-demo Steven$ docker version
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 19:05:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 19:13:00 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc7+dev
  GitCommit:        029124da7af7360afa781a0234d1b083550f797c
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
coffee:grpc-web-istio-demo Steven$

Steven$ cat server.Dockerfile
FROM golang:1.12 as builder
MAINTAINER Venil Noronha <veniln@vmware.com>

WORKDIR /root/go/src/github.com/venilnoronha/grpc-web-istio-demo/
COPY ./ .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o bin/server ./cmd/server.go

FROM scratch
WORKDIR /bin/
COPY --from=builder /root/go/src/github.com/venilnoronha/grpc-web-istio-demo/bin/server .
ENTRYPOINT [ "/bin/server" ]
EXPOSE 9000

coffee:docker Steven$ go version
go version go1.12.5 darwin/amd64
coffee:docker Steven$ 

coffee:grpc-web-istio-demo Steven$ make build-server
docker build -f docker/server.Dockerfile -t vnoronha/grpc-web-istio-demo:server .
Sending build context to Docker daemon  656.9kB
Step 1/10 : FROM golang:1.12 as builder
 ---> 9fe4cdc1f173
Step 2/10 : MAINTAINER Venil Noronha <veniln@vmware.com>
 ---> Using cache
 ---> d1ae7de93afa
Step 3/10 : WORKDIR /root/go/src/github.com/venilnoronha/grpc-web-istio-demo/
 ---> Using cache
 ---> f295c0eaff22
Step 4/10 : COPY ./ .
 ---> Using cache
 ---> 1a53dc2ab840
Step 5/10 : RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o bin/server ./cmd/server.go
 ---> Running in 68736f52fe41
Fetching https://golang.org/x/net?go-get=1
Fetching https://gopkg.in/kyokomi/emoji.v1?go-get=1
Fetching https://google.golang.org/grpc?go-get=1
go: finding github.com/golang/protobuf v1.2.0
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
get "golang.org/x/net": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc?go-get=1
go: finding google.golang.org/grpc v1.18.0
go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
Parsing meta tags from https://gopkg.in/kyokomi/emoji.v1?go-get=1 (status code 200)
get "gopkg.in/kyokomi/emoji.v1": found meta tag get.metaImport{Prefix:"gopkg.in/kyokomi/emoji.v1", VCS:"git", RepoRoot:"https://gopkg.in/kyokomi/emoji.v1"} at https://gopkg.in/kyokomi/emoji.v1?go-get=1
go: finding gopkg.in/kyokomi/emoji.v1 v1.5.1
Fetching https://honnef.co/go/tools?go-get=1
Fetching https://golang.org/x/tools?go-get=1
Fetching https://google.golang.org/appengine?go-get=1
Fetching https://golang.org/x/sync?go-get=1
Fetching https://golang.org/x/oauth2?go-get=1
Fetching https://cloud.google.com/go?go-get=1
Fetching https://golang.org/x/lint?go-get=1
Parsing meta tags from https://golang.org/x/sync?go-get=1 (status code 200)
get "golang.org/x/sync": found meta tag get.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at https://golang.org/x/sync?go-get=1
go: finding github.com/client9/misspell v0.3.4
Parsing meta tags from https://golang.org/x/lint?go-get=1 (status code 200)
Parsing meta tags from https://google.golang.org/appengine?go-get=1 (status code 200)
get "google.golang.org/appengine": found meta tag get.metaImport{Prefix:"google.golang.org/appengine", VCS:"git", RepoRoot:"https://github.com/golang/appengine"} at https://google.golang.org/appengine?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
Parsing meta tags from https://golang.org/x/oauth2?go-get=1 (status code 200)
get "golang.org/x/oauth2": found meta tag get.metaImport{Prefix:"golang.org/x/oauth2", VCS:"git", RepoRoot:"https://go.googlesource.com/oauth2"} at https://golang.org/x/oauth2?go-get=1
get "golang.org/x/lint": found meta tag get.metaImport{Prefix:"golang.org/x/lint", VCS:"git", RepoRoot:"https://go.googlesource.com/lint"} at https://golang.org/x/lint?go-get=1
get "golang.org/x/tools": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools?go-get=1
go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
go: finding golang.org/x/tools v0.0.0-20180828015842-6cd1fcedba52
Parsing meta tags from https://cloud.google.com/go?go-get=1 (status code 200)
get "cloud.google.com/go": found meta tag get.metaImport{Prefix:"cloud.google.com/go", VCS:"git", RepoRoot:"https://code.googlesource.com/gocloud"} at https://cloud.google.com/go?go-get=1
Parsing meta tags from https://honnef.co/go/tools?go-get=1 (status code 200)
get "honnef.co/go/tools": found meta tag get.metaImport{Prefix:"honnef.co/go/tools", VCS:"git", RepoRoot:"https://github.com/dominikh/go-tools"} at https://honnef.co/go/tools?go-get=1
go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
go: finding google.golang.org/appengine v1.1.0
go: finding honnef.co/go/tools v0.0.0-20180728063816-88497007e858
go: finding cloud.google.com/go v0.26.0
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
get "golang.org/x/sys": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys?go-get=1
go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: finding github.com/golang/mock v1.1.1
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
get "golang.org/x/text": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text?go-get=1
Fetching https://google.golang.org/genproto?go-get=1
go: finding golang.org/x/text v0.3.0
Parsing meta tags from https://google.golang.org/genproto?go-get=1 (status code 200)
get "google.golang.org/genproto": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at https://google.golang.org/genproto?go-get=1
go: finding google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: finding github.com/kisielk/gotool v1.0.0
go: downloading google.golang.org/grpc v1.18.0
go: downloading github.com/golang/protobuf v1.2.0
go: downloading gopkg.in/kyokomi/emoji.v1 v1.5.1
go: extracting gopkg.in/kyokomi/emoji.v1 v1.5.1
go: extracting github.com/golang/protobuf v1.2.0
go: extracting google.golang.org/grpc v1.18.0
go: downloading google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: downloading golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: downloading golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: extracting golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: extracting golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: downloading golang.org/x/text v0.3.0
go: extracting google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: extracting golang.org/x/text v0.3.0
errors
internal/cpu
math/bits
internal/bytealg
math
runtime/internal/atomic
runtime/internal/sys
runtime/internal/math
runtime
unicode/utf8
strconv
internal/race
sync/atomic
unicode
internal/testlog
encoding
unicode/utf16
internal/nettrace
internal/x/net/dns/dnsmessage
container/list
crypto/internal/subtle
crypto/subtle
crypto/rc4
internal/x/crypto/cryptobyte/asn1
internal/x/crypto/curve25519
google.golang.org/grpc/resolver
google.golang.org/grpc/resolver/passthrough
sync
io
reflect
syscall
time
sort
internal/fmtsort
internal/poll
internal/syscall/unix
bytes
os
bufio
encoding/binary
fmt
encoding/base64
strings
context
encoding/json
log
compress/flate
hash
hash/crc32
github.com/golang/protobuf/proto
compress/gzip
golang.org/x/net/internal/timeseries
html
path/filepath
io/ioutil
net/url
text/template/parse
text/template
html/template
internal/singleflight
math/rand
net
crypto/cipher
crypto/aes
math/big
crypto/rand
crypto
crypto/des
crypto/elliptic
crypto/internal/randutil
crypto/sha512
encoding/asn1
crypto/hmac
crypto/md5
crypto/rsa
crypto/ecdsa
crypto/sha1
crypto/sha256
crypto/dsa
encoding/hex
encoding/pem
crypto/x509/pkix
internal/x/crypto/cryptobyte
internal/x/crypto/internal/chacha20
internal/x/crypto/poly1305
internal/x/crypto/chacha20poly1305
crypto/x509
internal/x/crypto/hkdf
internal/x/text/transform
internal/x/text/unicode/bidi
internal/x/text/secure/bidirule
crypto/tls
internal/x/text/unicode/norm
internal/x/net/idna
net/textproto
internal/x/net/http/httpguts
internal/x/net/http/httpproxy
internal/x/net/http2/hpack
mime
mime/quotedprintable
net/http/httptrace
net/http/internal
mime/multipart
path
text/tabwriter
net/http
google.golang.org/grpc/grpclog
google.golang.org/grpc/connectivity
google.golang.org/grpc/credentials/internal
google.golang.org/grpc/credentials
google.golang.org/grpc/internal
google.golang.org/grpc/metadata
google.golang.org/grpc/balancer
google.golang.org/grpc/balancer/base
google.golang.org/grpc/balancer/roundrobin
google.golang.org/grpc/codes
google.golang.org/grpc/encoding
google.golang.org/grpc/encoding/proto
google.golang.org/grpc/internal/grpcrand
google.golang.org/grpc/internal/backoff
github.com/golang/protobuf/ptypes/any
github.com/golang/protobuf/ptypes/duration
github.com/golang/protobuf/ptypes/timestamp
github.com/golang/protobuf/ptypes
google.golang.org/grpc/binarylog/grpc_binarylog_v1
google.golang.org/genproto/googleapis/rpc/status
google.golang.org/grpc/status
regexp/syntax
regexp
google.golang.org/grpc/internal/binarylog
golang.org/x/sys/unix
golang.org/x/net/trace
google.golang.org/grpc/internal/channelz
google.golang.org/grpc/internal/envconfig
google.golang.org/grpc/internal/grpcsync
golang.org/x/text/transform
golang.org/x/text/unicode/bidi
golang.org/x/text/unicode/norm
golang.org/x/text/secure/bidirule
golang.org/x/net/http2/hpack
golang.org/x/net/idna
google.golang.org/grpc/internal/syscall
google.golang.org/grpc/keepalive
google.golang.org/grpc/peer
golang.org/x/net/http/httpguts
google.golang.org/grpc/stats
golang.org/x/net/http2
google.golang.org/grpc/tap
google.golang.org/grpc/naming
google.golang.org/grpc/resolver/dns
net/http/httputil
github.com/golang/protobuf/protoc-gen-go/descriptor
golang.org/x/net/context
gopkg.in/kyokomi/emoji.v1
google.golang.org/grpc/internal/transport
google.golang.org/grpc
github.com/venilnoronha/grpc-web-istio-demo/proto
google.golang.org/grpc/reflection/grpc_reflection_v1alpha
# github.com/venilnoronha/grpc-web-istio-demo/proto
proto/emoji.pb.go:25:11: undefined: proto.ProtoPackageIsVersion3
google.golang.org/grpc/reflection
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v -o bin/server ./cmd/server.go' returned a non-zero code: 2
make: *** [build-server] Error 2
coffee:grpc-web-istio-demo Steven$

**Comment by hanoisteve** [comment]
It might be related to this issue:  https://github.com/golang/dep/issues/2083

**Comment by venilnoronha** [comment]
Can you just change the version in the following line to `v1.3.1` and try running `make build-server` again?

https://github.com/venilnoronha/grpc-web-istio-demo/blob/539a2bd1a3e67e4be25246dba3d7c167510a291d/go.mod#L4

**Comment by venilnoronha** [comment]
If that above thing doesn't work, can you run `git apply proto.patch.txt` with the following file and try running `make build-server`?

[proto.patch.txt](https://github.com/venilnoronha/grpc-web-istio-demo/files/3313022/proto.patch.txt)

**Comment by hanoisteve** [comment]
Ok, I will try this now

**Comment by hanoisteve** [comment]
Yep, the first change resolved it and I did not need to apply the patch

**Comment by venilnoronha** [comment]
Awesome! Let me know if you'd like to submit a PR with the fix.

**Comment by venilnoronha** [comment]
@hanoisteve thanks for reporting the issue. I've fixed it in 5f9ab59e60412365043992441b432dddd83d11fc.
