### ISSUE TITLE
where is EnvoyFilter?

### ISSUE THREAD

**Issue by xmlking** [venilnoronha/grpc-web-istio-demo#3]
This repo don't have `EnvoyFilter` described in the blog https://venilnoronha.io/seamless-cloud-native-apps-with-grpc-web-and-istio

wonder if this repo is not in sync with blogs! which instructions are correct/latest ?

**Comment by xmlking** [comment]
is this the reasoning `EnvoyFilter` deployment not needed ?  https://github.com/istio/istio/pull/10064

**Comment by venilnoronha** [comment]
That's correct. You don't need the `EnvoyFilter` configuration if you're running a recent version of Istio.
